### ISSUE TITLE
Remove the english words that does not appear in the dictionary

### ISSUE THREAD

**Issue by samitkapoor** [samitkapoor/wordle#3]
You will find a lot of 5-letter words in [lib/constants/words.dart](https://github.com/samitkapoor/wordle/blob/master/lib/constants/words.dart).

Your task is to remove those words that on googling do not appear in the dictionary.

You can help by removing as many words as you can.

**Comment by iskhakov-s** [comment]
I'll try. I'll use the enchant spellchecking library to check valid words and double check all of the words that don't show up.

**Comment by iskhakov-s** [comment]
How strict should the checking be @samitkapoor ? Should obscure or archaic words/conjugations of words be included, like _brans_, _tippy_, or _blest_? Should proper nouns like _jutes_ or _tommy_ be excluded? Or should I only exclude words that are definitely not in the dictionary?

**Comment by samitkapoor** [comment]
Hey @iskhakov-s !
Archaic words should not be there.
Conjugations are allowed.
Proper nouns are not allowed.
Definitely remove the words that are not a part of dictionary.
